import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class student extends javax.swing.JFrame {

    
    
    public student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        fathersname = new javax.swing.JTextField();
        rollno = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        yearofstudy = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        bloodgroup = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        upload = new javax.swing.JButton();
        generatecard = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Student ID Card Input Form ");
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 21, -1, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Father's Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Roll No.:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("course:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Year Of Study:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Address:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("contact:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Blood Group:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("D.O.B:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Upload Photo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 150, -1));

        fathersname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fathersname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathersnameActionPerformed(evt);
            }
        });
        getContentPane().add(fathersname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 150, -1));

        rollno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoActionPerformed(evt);
            }
        });
        getContentPane().add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 150, -1));

        course.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 150, -1));

        yearofstudy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yearofstudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearofstudyActionPerformed(evt);
            }
        });
        getContentPane().add(yearofstudy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 150, -1));

        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 180, -1));

        contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 180, -1));

        bloodgroup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(bloodgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 180, -1));

        dob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 180, -1));

        upload.setBackground(new java.awt.Color(204, 204, 204));
        upload.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        upload.setText("Upload");
        upload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        getContentPane().add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 190, -1));

        generatecard.setBackground(new java.awt.Color(51, 255, 51));
        generatecard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        generatecard.setForeground(new java.awt.Color(255, 255, 255));
        generatecard.setText("Generate Card");
        generatecard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatecardActionPerformed(evt);
            }
        });
        getContentPane().add(generatecard, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 124, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
   name.setText("");
        fathersname.setText("");
        rollno.setText("");
        contact.setText("");
          course.setText("");
            yearofstudy.setText("");
              address.setText("");
                bloodgroup.setText("");
                  
        photoData = null; 
        this.dispose();       
    }//GEN-LAST:event_cancelActionPerformed

    private void generatecardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatecardActionPerformed
        String studentName = name.getText();
    String fatherName = fathersname.getText();
    String rollNumber = rollno.getText();
    String studentCourse = course.getText();
    String studyYear = yearofstudy.getText();
    String studentAddress = address.getText();
    String contactNumber = contact.getText();
    String bloodGroup = bloodgroup.getText();
    java.util.Date dobValue = dob.getDate();
    Date sqlDob = new Date(dobValue.getTime()); // Convert to SQL Date

    // Assuming you will handle photo as a Blob (binary data)
    // Here you can add code to handle photo upload using the 'upload' button
    

    // Database connection and insertion
    String url = "jdbc:mysql://localhost:3306/idcard";
    String username = "root";
    String password = "";  // Use your own database password

    try {
        Connection conn = DriverManager.getConnection(url, username, password);

        String query = "INSERT INTO students (name, fathers_name, roll_no, course, year_of_study, address, contact, blood_group, dob, photo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,?)";
        PreparedStatement stmt = conn.prepareStatement(query);

        stmt.setString(1, studentName);
        stmt.setString(2, fatherName);
        stmt.setString(3, rollNumber);
        stmt.setString(4, studentCourse);
        stmt.setString(5, studyYear);
        stmt.setString(6, studentAddress);
        stmt.setString(7, contactNumber);
        stmt.setString(8, bloodGroup);
        stmt.setDate(9, sqlDob);
        stmt.setBytes(10, photoData);

        int rowsInserted = stmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Student details saved successfully!");
             Previewstudent ps=new Previewstudent(studentName,fatherName,rollNumber,contactNumber,studentCourse,studyYear,studentAddress,bloodGroup,sqlDob,photoData);
                ps.setVisible(true);
        }
        
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }

    }//GEN-LAST:event_generatecardActionPerformed
private byte[] photoData;
    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select an Image");
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        try {
            photoData = Files.readAllBytes(selectedFile.toPath()); // Read the file as byte array
            JOptionPane.showMessageDialog(this, "Photo uploaded successfully!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error uploading photo: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_uploadActionPerformed

    private void fathersnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathersnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathersnameActionPerformed

    private void rollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void yearofstudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearofstudyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearofstudyActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
mainmenu m=new mainmenu();
m.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField bloodgroup;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField course;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField fathersname;
    private javax.swing.JButton generatecard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rollno;
    private javax.swing.JButton upload;
    private javax.swing.JTextField yearofstudy;
    // End of variables declaration//GEN-END:variables
}
